import sys
import os
import ssl
import pyrebase
import google.oauth2.credentials
from google.cloud import firestore
from file_util import get_filenames, fetch_files, find_files, find_original_files, find_artifacts
from execute_files import execute_files


ssl._create_default_https_context = ssl._create_unverified_context


config = {
  "apiKey": "AIzaSyDm7t3kFLtOriXhZyOOJReon1qnuubUbvE",
  "authDomain": "re3-fb.firebaseapp.com",
  "databaseURL": "https://re3-fb.firebaseio.com",
  "projectId": "re3-fb",
  "storageBucket": "re3-fb.appspot.com",
  "messagingSenderId": "121193880841",
  "appId": "1:121193880841:web:4efade68aa5339e1f487d8",
  "measurementId": "G-4PKZCP0PP0"
}


firebase = pyrebase.initialize_app(config)
auth_client = firebase.auth()
storage_client = firebase.storage()


project_dir = "/usr/workdir/project"


def main():
    user = auth_client.sign_in_anonymous()
    token = user['idToken']
    credentials = google.oauth2.credentials.Credentials(token)

    project_ref = sys.argv[1]
    r_version = sys.argv[2]
    ref_base = os.path.basename(project_ref)
    print("Project reference:", ref_base)

    db_client = firestore.Client(project=config["projectId"],
                                 credentials=credentials)

    doc_ref = db_client.document(project_ref)

    files = get_filenames(db_client, project_ref)
    fetch_files(files, project_dir)

    original_files = find_original_files(project_dir)
    files_to_exec = find_files(project_dir)

    for f in files_to_exec:
        res = execute_files(f, r_version)
        filename = os.path.basename(f)
        print(f'FILENAME: {filename.strip()}\nRESULT: {res}')

    artifacts = find_artifacts(project_dir, original_files)

    for f in artifacts:
        filename = os.path.basename(f)
        print(f'Found file generated by project: {filename}')
        storage_path = f'artifacts/{filename}'
        storage_client.child(storage_path).put(f)
        artifact_url = storage_client.child(storage_path).get_url(token)
        doc_ref.update({'artifacts': firestore.ArrayUnion([{"url": artifact_url, "filename": filename}])})

    auth_client.delete_user_account(token)


if __name__ == "__main__":
    main()