survey$male <- ifelse(survey$gender==1, 1, 0)
mean(survey$male)
sd(survey$male)
mean(as.numeric(as.character(survey$age)))
mean(as.numeric(as.character(survey$education)))
sum(survey$age==1)/nrow(survey)
sum(survey$age==2)/nrow(survey)
sum(survey$age==3)/nrow(survey)
sum(survey$age==4 | survey$age==5)/nrow(survey)
sum(survey$education==1)/nrow(survey)
sum(survey$education==2)/nrow(survey)
sum(survey$education==3)/nrow(survey)
sum(survey$education==4)/nrow(survey)
survey$ideology <- as.numeric(as.character(survey$ideology_1))
mean(survey$ideology)